### PR TITLE
Update download.html

### PR DESCRIPTION
**Pull request by alanbuxey**
minor typo fix

### CODE REVIEW

**Comment by arr2036** [comment]
If I added the new site in a separate branch, would you mind making similar fixups?

**Comment by alanbuxey** [comment]
once these recent ones are done, no, I wouldnt mind ;-)

**Comment by alanbuxey** [comment]
I dont mind making such fixups...... would be nice to have the old site as
good as it can be whilst its still around

**Comment by arr2036** [comment]
Yes, just be aware that there's no process to automatically merge the content you're fixing to the new website, so the typos will have to be fixed twice, else the spellings will regress.

**Comment by arr2036** [comment]
The new code is up now in the pilot_interactive branch.

**Pull request merged**
